version: '3.8'

services:
  frontend:
    build:
      context: ../UCryptPortal
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    networks:
      - uCryptNetwork
    depends_on:
      - ucrypt-app

  ucrypt-app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/ucrypt
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Khan54321@
      SPRING_PROFILES_ACTIVE: dev,docker
      BASIC_FOLDER_PATH: /data
    volumes:
      - data-volume:/data
    networks:
      - uCryptNetwork

volumes:
  data-volume:

networks:
  uCryptNetwork:
    driver: bridge
